<?php
/** Insurance page metadata, matching the supplied mock-ups. */
defined( 'ABSPATH' ) || exit;
return array(
	'services/how-to-claim' => array( 'title' => 'วิธีแจ้งเคลมประกันรถยนต์', 'description' => 'ขั้นตอนแจ้งเคลมประกันรถยนต์ การเตรียมเอกสาร และการติดตามสถานะเคลมกับบริษัทประกัน', 'classes' => 'claims-page', 'styles' => array( 'pages.css', 'navigation.css', 'hero-layout.css' ) ),
	'compare' => array( 'title' => 'ขอใบเสนอราคา — บอกรายละเอียดรถของคุณ', 'classes' => 'compare-wizard-page', 'styles' => array( 'pages.css', 'navigation.css', 'compare.css' ) ),
	'privacy-policy' => array( 'title' => 'นโยบายความเป็นส่วนตัว', 'classes' => 'legal-page', 'styles' => array( 'pages.css', 'navigation.css', 'legal.css' ) ),
	'terms-and-conditions' => array( 'title' => 'ข้อกำหนดและเงื่อนไข', 'classes' => 'legal-page', 'styles' => array( 'pages.css', 'navigation.css', 'legal.css' ) ),

		'home-v2' => array(
			'title' => 'ประกันรถยนต์ที่ใช่ ให้เราช่วยคัดให้',
			'classes' => 'home-v2-page',
			'styles' => array( 'pages.css', 'home-reference.css', 'navigation.css', 'hero-layout.css', 'home-v2.css' ),
		),
		'motorbike-insurance' => array(
			'title' => 'ประกันรถมอเตอร์ไซค์',
			'classes' => 'product-detail-page',
			'menu_group' => 'other',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css', 'product-hero.css' ),
		),
		'van-insurance' => array(
			'title' => 'ประกันรถตู้',
			'classes' => 'product-detail-page',
			'menu_group' => 'other',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css', 'product-hero.css' ),
		),
		'truck-insurance' => array(
			'title' => 'ประกันรถบรรทุก',
			'classes' => 'product-detail-page',
			'menu_group' => 'other',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css', 'product-hero.css' ),
		),
		'personal-accident-insurance' => array(
			'title' => 'ประกันอุบัติเหตุ (PA)',
			'classes' => 'product-detail-page',
			'menu_group' => 'other',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css', 'product-hero.css' ),
		),
		'cancer-insurance' => array(
			'title' => 'ประกันมะเร็ง',
			'classes' => 'product-detail-page',
			'menu_group' => 'other',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css', 'product-hero.css' ),
		),
		'car-insurance/muang-thai-insurance' => array(
			'title' => 'เมืองไทยประกันภัย',
			'classes' => 'product-detail-page muang-thai-page',
			'menu_group' => 'companies',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css', 'muang-thai.css' ),
		),
		'car-insurance/roojai-insurance' => array(
			'title' => 'Roojai',
			'classes' => 'product-detail-page',
			'menu_group' => 'companies',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css' ),
		),
		'car-insurance/viriyah-insurance' => array(
			'title' => 'วิริยะประกันภัย',
			'classes' => 'product-detail-page',
			'menu_group' => 'companies',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css' ),
		),
		'car-insurance/chubb-insurance' => array(
			'title' => 'Chubb',
			'classes' => 'product-detail-page',
			'menu_group' => 'companies',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css' ),
		),
		'car-insurance/bangkok-insurance' => array(
			'title' => 'กรุงเทพประกันภัย',
			'classes' => 'product-detail-page',
			'menu_group' => 'companies',
			'styles' => array( 'pages.css', 'navigation.css', 'products-v2.css' ),
		),
		'about-us' => array(
			'title' => 'รู้จัก KUDHai คัดประกันด้วยความเข้าใจ',
			'description' => 'รู้จัก KUDHai คัดประกันด้วยความเข้าใจ — KUDHai',
			'classes' => 'about-page',
			'styles' => array( 'pages.css', 'navigation.css', 'hero-layout.css' ),
		),
		'mun-lamert' => array(
			'title' => 'การเรียกร้องค่าสินไหมจากมูลละเมิด',
			'description' => 'การเรียกร้องค่าสินไหมจากมูลละเมิด — KUDHai',
			'classes' => 'compensation-page',
			'styles' => array( 'pages.css', 'navigation.css', 'hero-layout.css', 'mun-overview.css' ),
		),
		'mun-lamert/what-is' => array(
			'title' => 'มูลละเมิดคืออะไร',
			'description' => 'อธิบายคำว่า “มูลละเมิด” ในบริบทอุบัติเหตุรถยนต์ ความเกี่ยวข้องกับผู้เสียหาย ผู้เอาประกันภัย และบริษัทประกัน พร้อมหลักจากคู่มือตีความกรมธรรม์รถยนต์',
			'classes' => 'mun-detail-page mun-what-is-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/repair-cost' => array(
			'title' => 'ค่าซ่อมรถจากคู่กรณี',
			'description' => 'รถเสียหายจากอุบัติเหตุ ดูเอกสารค่าซ่อมรถ ใบเสนอราคา ใบเสร็จ และหลักฐานความเสียหายตามขั้นตอนบริษัทประกันโดยตรง',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/medical-expenses' => array(
			'title' => 'ค่ารักษาพยาบาลจากอุบัติเหตุรถยนต์',
			'description' => 'เข้าใจค่ารักษาพยาบาลและค่าใช้จ่ายเกี่ยวเนื่องจากอุบัติเหตุรถยนต์ ตามคู่มือตีความ พร้อมหลักฐานทางการแพทย์ที่ควรเก็บ',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/lost-income' => array(
			'title' => 'ค่าขาดรายได้จากอุบัติเหตุรถยนต์',
			'description' => 'อุบัติเหตุทำให้หยุดงานหรือรายได้ลด? ดูหลักจากคู่มือตีความเรื่องรายได้และความสามารถประกอบการงาน พร้อมแนวทางเตรียมหลักฐาน',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/loss-of-use' => array(
			'title' => 'ค่าขาดประโยชน์จากการใช้รถ',
			'description' => 'รถเป็นฝ่ายถูกและต้องเข้าอู่? ดูหลักฐานและขั้นตอนเรียกร้องค่าขาดประโยชน์จากการใช้รถ อ้างอิงข้อมูลการเรียกร้องค่าสินไหมโดยตรง',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/injury' => array(
			'title' => 'บาดเจ็บจากอุบัติเหตุรถยนต์เรียกร้องอะไรได้',
			'description' => 'บาดเจ็บจากรถชน อย่าดูแค่ค่ารักษา คู่มือตีความยังกล่าวถึงค่าใช้จ่ายเกี่ยวเนื่อง การรักษาในอนาคต พาหนะ และผลกระทบต่อความสามารถทำงาน',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/how-to-claim' => array(
			'title' => 'วิธีเรียกร้องค่าเสียหายจากคู่กรณี',
			'description' => 'เช็กลำดับการเรียกร้องค่าเสียหายหลังรถชน ตั้งแต่แจ้งเหตุ แยกรายการความเสียหาย เตรียมเอกสาร จนถึงยื่นบริษัทประกัน อ้างอิงขั้นตอนบริษัทประกันโดยตรง',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/documents' => array(
			'title' => 'เอกสารเรียกร้องค่าเสียหายจากประกันคู่กรณี',
			'description' => 'รวมเอกสารที่บริษัทประกันระบุสำหรับค่าซ่อมรถ ค่าขาดประโยชน์ บาดเจ็บ และเสียชีวิต พร้อมแยกเป็นหมวดเพื่อเตรียมก่อนยื่น',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/depreciation' => array(
			'title' => 'ค่าเสื่อมราคารถหลังเกิดอุบัติเหตุ',
			'description' => 'ตรวจให้ชัดก่อนเชื่อเรื่องค่าเสื่อมราคารถ: คู่มือตีความพูดถึงการเสื่อมราคาในข้อยกเว้นรถคันเอาประกัน ขณะที่ผู้รับประกันภัยระบุหลักฐานค่าเสื่อมราคารถของคู่กรณี',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/death' => array(
			'title' => 'เสียชีวิตจากอุบัติเหตุรถยนต์ สิทธิทายาท',
			'description' => 'คู่มือตีความรวมทายาทโดยธรรมของผู้ประสบภัยที่เสียชีวิต และยกตัวอย่างค่าขาดไร้อุปการะ ค่าใช้จ่ายจำเป็นกรณีเสียชีวิต และรายการอื่นที่ต้องพิจารณา',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/compensation' => array(
			'title' => 'รถชนเรียกร้องค่าเสียหายอะไรได้บ้าง',
			'description' => 'รวมหมวดความเสียหายที่คู่มือตีความกรมธรรม์รถยนต์กล่าวถึง ทั้งค่ารักษา ค่าใช้จ่ายเกี่ยวเนื่อง ขาดรายได้ ผลกระทบต่อการทำงาน และกรณีเสียชีวิต',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/claim-rejected' => array(
			'title' => 'ประกันคู่กรณีไม่จ่าย',
			'description' => 'เมื่อยอดที่เรียกร้องกับยอดที่บริษัทพิจารณาไม่ตรงกัน ให้แยกตรวจความรับผิด รายการความเสียหาย หลักฐาน และขอบเขตกรมธรรม์ก่อนสรุปว่า “ประกันไม่จ่าย”',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'mun-lamert/car-accident' => array(
			'title' => 'มูลละเมิดจากอุบัติเหตุรถยนต์',
			'description' => 'รถชนแล้วใครต้องรับผิด? แยกผู้ก่อเหตุ ผู้เสียหาย และบริษัทประกัน พร้อมหลักการจากคู่มือตีความกรมธรรม์รถยนต์',
			'classes' => 'mun-detail-page',
			'styles' => array( 'pages.css', 'navigation.css', 'mun-details-v2.css', 'mun-what-is.css' ),
		),
		'contact-us' => array(
			'title' => 'ติดต่อ KUDHai มีคำถาม คุยกับเราได้',
			'description' => 'ติดต่อ KUDHai มีคำถาม คุยกับเราได้ — KUDHai',
			'classes' => 'contact-page',
			'styles' => array( 'pages.css', 'navigation.css', 'hero-layout.css' ),
		),
		'articles' => array(
			'title' => 'เรื่องประกันรถยนต์ อ่านให้เข้าใจ',
			'description' => 'เรื่องประกันรถยนต์ อ่านให้เข้าใจ — KUDHai',
			'classes' => 'articles-page',
			'styles' => array( 'pages.css', 'navigation.css', 'hero-layout.css' ),
		),
		'compulsory' => array(
			'title' => 'พ.ร.บ. รถยนต์',
			'description' => 'รู้จัก พ.ร.บ. รถยนต์ ความคุ้มครองพื้นฐาน เอกสารใช้สิทธิ และคำถามที่พบบ่อย',
			'classes' => 'insurance-page insurance-detail compulsory-page',
			'styles' => array( 'pages.css', 'insurance.css', 'insurance-details.css', 'compulsory.css', 'navigation.css', 'hero-layout.css', 'compulsory-hero-mobile.css' ),
		),
		'insurance-1' => array(
			'title' => 'ประกันรถยนต์ชั้น 1',
			'description' => 'ประกันรถยนต์ชั้น 1 — เข้าใจความคุ้มครอง ข้อยกเว้น และรายละเอียดก่อนเลือกแผน',
			'classes' => 'insurance-page insurance-detail detail-1',
			'styles' => array( 'pages.css', 'insurance.css', 'insurance-details.css', 'navigation.css', 'hero-layout.css', 'insurance-overview.css' ),
		),
		'insurance-2' => array(
			'title' => 'ประกันรถยนต์ชั้น 2',
			'description' => 'ประกันรถยนต์ชั้น 2 — เข้าใจความคุ้มครอง ข้อยกเว้น และรายละเอียดก่อนเลือกแผน',
			'classes' => 'insurance-page insurance-detail detail-2',
			'styles' => array( 'pages.css', 'insurance.css', 'insurance-details.css', 'navigation.css', 'hero-layout.css', 'insurance-overview.css' ),
		),
		'insurance-2plus' => array(
			'title' => 'ประกันรถยนต์ชั้น 2+',
			'description' => 'ประกันรถยนต์ชั้น 2+ — เข้าใจความคุ้มครอง ข้อยกเว้น และรายละเอียดก่อนเลือกแผน',
			'classes' => 'insurance-page insurance-detail detail-2plus',
			'styles' => array( 'pages.css', 'insurance.css', 'insurance-details.css', 'navigation.css', 'hero-layout.css', 'insurance-overview.css' ),
		),
		'insurance-3' => array(
			'title' => 'ประกันรถยนต์ชั้น 3',
			'description' => 'ประกันรถยนต์ชั้น 3 — เข้าใจความคุ้มครอง ข้อยกเว้น และรายละเอียดก่อนเลือกแผน',
			'classes' => 'insurance-page insurance-detail detail-3',
			'styles' => array( 'pages.css', 'insurance.css', 'insurance-details.css', 'navigation.css', 'hero-layout.css', 'insurance-overview.css' ),
		),
		'insurance-3plus' => array(
			'title' => 'ประกันรถยนต์ชั้น 3+',
			'description' => 'ทำความเข้าใจประกันรถยนต์ชั้น 3+ ความคุ้มครอง ข้อยกเว้น และคำถามที่พบบ่อย',
			'classes' => 'insurance-page insurance-3plus',
			'styles' => array( 'pages.css', 'insurance.css', 'insurance-3plus.css', 'navigation.css', 'hero-layout.css', 'insurance-overview.css' ),
		),
		'insurance-ev' => array(
			'title' => 'ประกันรถยนต์ไฟฟ้า',
			'description' => 'ประกันรถยนต์ไฟฟ้า — เข้าใจความคุ้มครอง ข้อยกเว้น และรายละเอียดก่อนเลือกแผน',
			'classes' => 'insurance-page insurance-detail detail-ev',
			'styles' => array( 'pages.css', 'insurance.css', 'insurance-details.css', 'navigation.css', 'hero-layout.css', 'insurance-overview.css' ),
		),
		'insurance-guide' => array(
			'title' => 'ประกันภัยรถยนต์ — คู่มือความคุ้มครอง',
			'description' => 'รู้จักประเภทประกันรถยนต์ และจุดที่ควรเปรียบเทียบให้เหมาะกับรถและงบของคุณ',
			'classes' => 'insurance-page insurance-detailed',
			'styles' => array( 'pages.css', 'insurance.css', 'navigation.css', 'hero-layout.css' ),
		),
		'insurance' => array(
			'title' => 'ประกันภัยรถยนต์ — เข้าใจความคุ้มครอง ก่อนเลือกแผน',
			'description' => 'รู้จักประเภทประกันรถยนต์ และจุดที่ควรเปรียบเทียบให้เหมาะกับรถและงบของคุณ',
			'classes' => 'insurance-page insurance-overview',
			'styles' => array( 'pages.css', 'insurance.css', 'navigation.css', 'hero-layout.css', 'insurance-overview.css' ),
		),
	);
